version: '3.8'

services:
  studienportal-db:
    image: mongo:latest
    container_name: studienportal-db
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 